## 00. PyTorch Fundamentals

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121



##Introduction to Tensors

###Creating tensors
PyTorch tensors are created using the command 'torch.Tensor()'

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Get number of dimention
scalar.ndim

0

In [4]:
# Get tensior back as Python int
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],

                        [[10,11,12],
                         [13,14,15],
                         [16,17,18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [13]:
TENSOR[1][1][1]

tensor(14)

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

### RANDOM TENSORS CONCEPT

Why random tensors?
- it is important because many neural network usually start with random set of numbers and then process it to better represent the data.


Process:

1. Start with random numbers
2. Look at data
3. Update random number
4. Look at data
5. Update random numbers

In [16]:
# Create a random tensor of shape (3,4)

random_tensor = torch.rand(3, 10,4)
random_tensor

tensor([[[0.3200, 0.5363, 0.4351, 0.5265],
         [0.7656, 0.7165, 0.6594, 0.3979],
         [0.7468, 0.8255, 0.2380, 0.1134],
         [0.3429, 0.0967, 0.0020, 0.0415],
         [0.9231, 0.9165, 0.0805, 0.7871],
         [0.3994, 0.0917, 0.9037, 0.9845],
         [0.1155, 0.1654, 0.1630, 0.1593],
         [0.3832, 0.7361, 0.2847, 0.1639],
         [0.9118, 0.9210, 0.8142, 0.8390],
         [0.8273, 0.1989, 0.5939, 0.7063]],

        [[0.8416, 0.2867, 0.6555, 0.6763],
         [0.6626, 0.4314, 0.7222, 0.2476],
         [0.2900, 0.3418, 0.7860, 0.5143],
         [0.0418, 0.2247, 0.4593, 0.4574],
         [0.9700, 0.7421, 0.4029, 0.6788],
         [0.5630, 0.5144, 0.8811, 0.7774],
         [0.7582, 0.4421, 0.4650, 0.9593],
         [0.6778, 0.3745, 0.7810, 0.1706],
         [0.8016, 0.8793, 0.4648, 0.3846],
         [0.0710, 0.9947, 0.0713, 0.5422]],

        [[0.8512, 0.4390, 0.9742, 0.7327],
         [0.3822, 0.2019, 0.3895, 0.9737],
         [0.7391, 0.7276, 0.8626, 0.6780],
       

In [17]:
# Create a random tensor with shape similar to image tensor
random_image_size_tensor = torch.rand(3, 244, 244)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [18]:
random_image_size_tensor

tensor([[[0.2477, 0.0753, 0.9713,  ..., 0.6531, 0.5804, 0.9993],
         [0.2360, 0.7776, 0.8128,  ..., 0.6596, 0.0964, 0.5080],
         [0.0288, 0.9432, 0.2283,  ..., 0.0640, 0.8834, 0.0504],
         ...,
         [0.6065, 0.6548, 0.1870,  ..., 0.5932, 0.1888, 0.4248],
         [0.7690, 0.8410, 0.6288,  ..., 0.0804, 0.8353, 0.4980],
         [0.9743, 0.7881, 0.5443,  ..., 0.4061, 0.2007, 0.0173]],

        [[0.6229, 0.7746, 0.2696,  ..., 0.2869, 0.0169, 0.7340],
         [0.6528, 0.8810, 0.5952,  ..., 0.7458, 0.9978, 0.1969],
         [0.3120, 0.7248, 0.7979,  ..., 0.1537, 0.3550, 0.8800],
         ...,
         [0.6200, 0.4772, 0.2880,  ..., 0.6383, 0.7278, 0.5198],
         [0.6727, 0.9151, 0.2638,  ..., 0.2634, 0.1303, 0.4654],
         [0.9852, 0.7321, 0.4971,  ..., 0.4279, 0.7327, 0.9117]],

        [[0.7471, 0.7095, 0.9106,  ..., 0.4992, 0.9081, 0.3655],
         [0.4567, 0.4128, 0.6309,  ..., 0.3570, 0.8785, 0.5836],
         [0.4380, 0.6869, 0.6185,  ..., 0.0319, 0.7776, 0.

In [23]:
#creating tensors composing of 0
zeros = torch.zeros(3,2)
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [25]:
#creating tensors composing of 1
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
zeros.dtype

torch.float32

###CREATING A RANGE OF TENSORS AND TENSORS-LIKE

In [35]:
# USE TORCH.RANGE(start, end, step)
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
one_to_ten_step= torch.arange(1,11 , 3)
one_to_ten_step

tensor([ 1,  4,  7, 10])

In [37]:
#Creating a tensor-like

In [39]:
ten_zero = torch.zeros_like(one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###TENSOR DATATYPE

**NOTE:** 3 big errors you'll run into with PyTorch & deep learning

    1. Tensors not right datatype
    2. Tensors not right shape
    3. Tensors not on the right device


In [47]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor?
                               device="cpu", # What device is your tensor on?
                               requires_grad=False) # track gradients with this tensor operator?
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [52]:
product = float_32_tensor * float_16_tensor
product

tensor([ 9., 36., 81.])