<a href="https://colab.research.google.com/github/Yughie/Mastering-Machine-Learning/blob/main/Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121



##Introduction to Tensors

###Creating tensors
PyTorch tensors are created using the command 'torch.Tensor()'

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#Get number of dimention
scalar.ndim

0

In [6]:
# Get tensior back as Python int
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],

                        [[10,11,12],
                         [13,14,15],
                         [16,17,18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [15]:
TENSOR[1][1][1]

tensor(14)

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([2, 3, 3])

### RANDOM TENSORS CONCEPT

Why random tensors?
- it is important because many neural network usually start with random set of numbers and then process it to better represent the data.


Process:

1. Start with random numbers
2. Look at data
3. Update random number
4. Look at data
5. Update random numbers

In [18]:
# Create a random tensor of shape (3,4)

random_tensor = torch.rand(3, 10,4)
random_tensor

tensor([[[0.3785, 0.7069, 0.0817, 0.2617],
         [0.2016, 0.7562, 0.0295, 0.9206],
         [0.6549, 0.8093, 0.7682, 0.4148],
         [0.3466, 0.1339, 0.7369, 0.7347],
         [0.2524, 0.7515, 0.9894, 0.7400],
         [0.1849, 0.5822, 0.4975, 0.3628],
         [0.9953, 0.1443, 0.3863, 0.9604],
         [0.6529, 0.5799, 0.4578, 0.6354],
         [0.4285, 0.0096, 0.2137, 0.3340],
         [0.2183, 0.5305, 0.4896, 0.4537]],

        [[0.7033, 0.6327, 0.5888, 0.7876],
         [0.7738, 0.4364, 0.4534, 0.7882],
         [0.4909, 0.7753, 0.1561, 0.9310],
         [0.0099, 0.2149, 0.4812, 0.4997],
         [0.5857, 0.0492, 0.2197, 0.0218],
         [0.5470, 0.3559, 0.4507, 0.3776],
         [0.0353, 0.8445, 0.8341, 0.3749],
         [0.8279, 0.4408, 0.7072, 0.7899],
         [0.2422, 0.0161, 0.8324, 0.5290],
         [0.6219, 0.1351, 0.7319, 0.6912]],

        [[0.3586, 0.7546, 0.9301, 0.5529],
         [0.4965, 0.5745, 0.9323, 0.9155],
         [0.5306, 0.8524, 0.3782, 0.9173],
       

In [22]:
# Create a random tensor with shape similar to image tensor
random_image_size_tensor = torch.rand(3, 244, 244)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [23]:
random_image_size_tensor

tensor([[[0.1932, 0.3776, 0.4614,  ..., 0.7411, 0.9378, 0.8186],
         [0.9562, 0.4780, 0.3852,  ..., 0.3483, 0.1331, 0.5338],
         [0.3097, 0.4154, 0.8109,  ..., 0.2650, 0.9504, 0.6116],
         ...,
         [0.4165, 0.7012, 0.3667,  ..., 0.5478, 0.9193, 0.3841],
         [0.7720, 0.5780, 0.0145,  ..., 0.7832, 0.8483, 0.9007],
         [0.7888, 0.8950, 0.3346,  ..., 0.5593, 0.4878, 0.7319]],

        [[0.8785, 0.0281, 0.9283,  ..., 0.5572, 0.4376, 0.8626],
         [0.1346, 0.1043, 0.9610,  ..., 0.1668, 0.2382, 0.9972],
         [0.9321, 0.4350, 0.5364,  ..., 0.5698, 0.8084, 0.5476],
         ...,
         [0.1398, 0.1408, 0.1298,  ..., 0.8926, 0.9135, 0.1557],
         [0.5354, 0.6838, 0.8911,  ..., 0.8972, 0.8476, 0.9880],
         [0.0961, 0.7751, 0.1842,  ..., 0.8222, 0.1914, 0.1421]],

        [[0.2259, 0.0697, 0.3757,  ..., 0.7434, 0.8858, 0.0140],
         [0.5213, 0.5335, 0.6538,  ..., 0.7538, 0.0529, 0.3441],
         [0.1718, 0.5835, 0.6096,  ..., 0.6655, 0.7961, 0.