## 00. PyTorch Fundamentals

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121



##Introduction to Tensors

###Creating tensors
PyTorch tensors are created using the command 'torch.Tensor()'

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Get number of dimention
scalar.ndim

0

In [4]:
# Get tensior back as Python int
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],

                        [[10,11,12],
                         [13,14,15],
                         [16,17,18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [13]:
TENSOR[1][1][1]

tensor(14)

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

### RANDOM TENSORS CONCEPT

Why random tensors?
- it is important because many neural network usually start with random set of numbers and then process it to better represent the data.


Process:

1. Start with random numbers
2. Look at data
3. Update random number
4. Look at data
5. Update random numbers

In [16]:
# Create a random tensor of shape (3,4)

random_tensor = torch.rand(3, 10,4)
random_tensor

tensor([[[0.2592, 0.2718, 0.4347, 0.2984],
         [0.5730, 0.9967, 0.5912, 0.9328],
         [0.2088, 0.9947, 0.6691, 0.2876],
         [0.4878, 0.8825, 0.1856, 0.0963],
         [0.3219, 0.2816, 0.4828, 0.2733],
         [0.2811, 0.1575, 0.6222, 0.3401],
         [0.5285, 0.6769, 0.7914, 0.4572],
         [0.0781, 0.3154, 0.5878, 0.7750],
         [0.5121, 0.7516, 0.0292, 0.4096],
         [0.4019, 0.6333, 0.7835, 0.9329]],

        [[0.7582, 0.1538, 0.7905, 0.8319],
         [0.0794, 0.6678, 0.5363, 0.3996],
         [0.7996, 0.8423, 0.1300, 0.0995],
         [0.8487, 0.1132, 0.6199, 0.4868],
         [0.0166, 0.2075, 0.0800, 0.1223],
         [0.8412, 0.6433, 0.5428, 0.2117],
         [0.3745, 0.9189, 0.3221, 0.6152],
         [0.8088, 0.7244, 0.6451, 0.4717],
         [0.7654, 0.9241, 0.0719, 0.9521],
         [0.3822, 0.0045, 0.9956, 0.8894]],

        [[0.9687, 0.4802, 0.8327, 0.6316],
         [0.6634, 0.9996, 0.7489, 0.8050],
         [0.4143, 0.3422, 0.0327, 0.7750],
       

In [17]:
# Create a random tensor with shape similar to image tensor
random_image_size_tensor = torch.rand(3, 244, 244)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [18]:
random_image_size_tensor

tensor([[[0.4846, 0.3731, 0.9058,  ..., 0.0274, 0.1158, 0.0818],
         [0.2331, 0.2077, 0.9426,  ..., 0.0100, 0.6298, 0.3648],
         [0.2901, 0.8343, 0.5561,  ..., 0.1794, 0.5829, 0.3904],
         ...,
         [0.8801, 0.5355, 0.8459,  ..., 0.5784, 0.8218, 0.8266],
         [0.4242, 0.6337, 0.0594,  ..., 0.8436, 0.9426, 0.7071],
         [0.2396, 0.9157, 0.5877,  ..., 0.3737, 0.5542, 0.5079]],

        [[0.8599, 0.7958, 0.8758,  ..., 0.0798, 0.3362, 0.0800],
         [0.9577, 0.8533, 0.6403,  ..., 0.8426, 0.0507, 0.0284],
         [0.3813, 0.4591, 0.3620,  ..., 0.2349, 0.5548, 0.0439],
         ...,
         [0.7577, 0.6988, 0.8017,  ..., 0.4239, 0.4567, 0.5103],
         [0.6481, 0.5592, 0.0602,  ..., 0.2627, 0.6968, 0.9920],
         [0.6252, 0.7471, 0.9688,  ..., 0.5883, 0.3359, 0.6470]],

        [[0.8205, 0.5553, 0.1616,  ..., 0.4309, 0.9231, 0.1316],
         [0.1612, 0.4335, 0.1451,  ..., 0.8948, 0.3384, 0.8515],
         [0.6884, 0.9039, 0.3821,  ..., 0.5891, 0.0840, 0.

In [19]:
#creating tensors composing of 0
zeros = torch.zeros(3,2)
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [20]:
#creating tensors composing of 1
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
zeros.dtype

torch.float32

###CREATING A RANGE OF TENSORS AND TENSORS-LIKE

In [23]:
# USE TORCH.RANGE(start, end, step)
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
one_to_ten_step= torch.arange(1,11 , 3)
one_to_ten_step

tensor([ 1,  4,  7, 10])

In [25]:
#Creating a tensor-like

In [26]:
ten_zero = torch.zeros_like(one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###TENSOR DATATYPE

**NOTE:** 3 big errors you'll run into with PyTorch & deep learning

    1. Tensors not right datatype
    2. Tensors not right shape
    3. Tensors not on the right device


In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor?
                               device="cpu", # What device is your tensor on?
                               requires_grad=False) # track gradients with this tensor operator?
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
product = float_32_tensor * float_16_tensor
product

tensor([ 9., 36., 81.])

### Manipulating Tensors (tensor)

Tensor operation includes
* Addition
* Subtraction
* Multiplication (Element-wise)
* Matrix Multiplication


In [34]:
# Create a tensor and add 10

tensor = torch.tensor([1,2,3])
tensor + 10
torch.add(tensor, 10)

tensor([11, 12, 13])

In [32]:
# Create a tensor and subtract 10

tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [33]:
# Create a tensor and multiply 10

tensor = torch.tensor([1,2,3])
tensor * 10

# Try out Pytorch  in-built funcrtion

torch.mul(tensor, 10)

tensor([10, 20, 30])

### MATRIX MULTIPLICATION

Two ways of multiplication in neural network and deep learning:
1. Multiplication (element-wise)
2. Matrix Multiplication (Dot product)


Two main rule in matix multiplication
1. **Inner dimension** must match
`(3, 2) @ (3, 2)`   - won't work
`(2, 3) @ (3, 2)`   - will work
`(3, 2) @ (2, 3)`   - will work

2. **Outer dimension*** will be the result shape of multiplying matrix
`(3, 2) @ (3, 2)`  - >  Error
`(2, 3) @ (3, 2)`  - > [2, 2]
`(3, 2) @ (2, 3)`  - > [3, 3]


In [37]:
# Element-wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
#Matrix Multiplication function
%%time
torch.matmul(tensor, tensor)

CPU times: user 478 µs, sys: 0 ns, total: 478 µs
Wall time: 376 µs


tensor(14)

In [45]:
# Matrix Multiplication using for loop
%%time
value = 0;
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.26 ms, sys: 14 µs, total: 3.27 ms
Wall time: 2.98 ms


***Note:*** Matrix Multiplication have less time comapre to for loop method

### COMMON ERROR IN DEEP LEARNING: SHAPE ERROR

In [48]:
tensor_A = torch.tensor([[1, 2],
                         [3,4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### ***TRANSPOSE:*** to fix problem with the shape issues
*Switches the axes or dimenstion of a given tensor



In [52]:
print(f"Original tensor_B: {tensor_B}")
print(f"Transposed tensor_B: {tensor_B.T}")

Original tensor_B: tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
Transposed tensor_B: tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [50]:
tensor_B.T
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, sum, mean, etc (tensor aggregation)

In [71]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
# Get the minimum value
torch.min(x), x.min()

(tensor(1), tensor(1))

In [73]:
# Get the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [74]:
#Get the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [75]:
# Get the average
# Note: The mean function only accept a dtype of float or coplex datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

### FINDING THE POSITIONAL min AND max

In [78]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [84]:
# Find the position of min and max in tensor
print(f"Position of min: {x.argmin()}")
print(f"Position of Max: {x.argmax()}")


Position of min: 0
Position of Max: 9
Position of average: tensor([], size=(1, 0), dtype=torch.int64)


## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way



In [91]:
import torch
x = torch. arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [92]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))